In [2]:
import torch
print(f"PyTorch version: {torch.__version__}")
print(f"CUDA available: {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"GPU: {torch.cuda.get_device_name(0)}")

PyTorch version: 2.5.1+cu121
CUDA available: True
GPU: NVIDIA GeForce RTX 2050


---
## Part 1: Tensors - The Building Block of Everything

A tensor is just a number container (like numpy arrays).

| Type | Dimensions | Example |
|------|-----------|--------|
| Scalar | 0D | Single number |
| Vector | 1D | List of numbers |
| Matrix | 2D | Table of numbers |
| 3D+ | 3D+ | Cube/hypercube |

Your neural network inputs, weights, and outputs are ALL tensors.

### 1.1 Creating tensors from Python data

In [2]:
# Creating tensors from Python data
scalar = torch.tensor(7)                        # just a number
vector = torch.tensor([1, 2, 3, 4, 5])          # 1D - like a list
matrix = torch.tensor([[1, 2, 3],
                        [4, 5, 6]])              # 2D - like a spreadsheet
cube   = torch.tensor([[[1, 2], [3, 4]],
                        [[5, 6], [7, 8]]])       # 3D

print(f"Scalar: {scalar}  -> shape: {scalar.shape}  -> dimensions: {scalar.ndim}D")
print(f"Vector: {vector}  -> shape: {vector.shape}  -> dimensions: {vector.ndim}D")
print(f"Matrix:\n{matrix}  -> shape: {matrix.shape}  -> dimensions: {matrix.ndim}D")
print(f"3D Tensor:\n{cube}  -> shape: {cube.shape}  -> dimensions: {cube.ndim}D")

# KEY INSIGHT: shape tells you the SIZE of each dimension
# matrix shape [2, 3] means: 2 rows, 3 columns
# cube shape [2, 2, 2] means: 2 layers, 2 rows, 2 columns

Scalar: 7  -> shape: torch.Size([])  -> dimensions: 0D
Vector: tensor([1, 2, 3, 4, 5])  -> shape: torch.Size([5])  -> dimensions: 1D
Matrix:
tensor([[1, 2, 3],
        [4, 5, 6]])  -> shape: torch.Size([2, 3])  -> dimensions: 2D
3D Tensor:
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])  -> shape: torch.Size([2, 2, 2])  -> dimensions: 3D


### 1.2 Common ways to create tensors

In [3]:
zeros = torch.zeros(3, 4)        # 3x4 matrix of zeros
ones  = torch.ones(2, 3)         # 2x3 matrix of ones
rand  = torch.rand(2, 3)         # 2x3 random values between 0 and 1
randn = torch.randn(2, 3)        # 2x3 random values (normal distribution)
arange = torch.arange(0, 10, 2)  # [0, 2, 4, 6, 8] - like Python range()
full  = torch.full((2, 3), 42)   # 2x3 matrix filled with 42

print(f"Zeros:\n{zeros}")
print(f"Random:\n{rand}")
print(f"Arange: {arange}")
print(f"Full of 42s:\n{full}")

Zeros:
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
Random:
tensor([[0.8285, 0.5552, 0.1205],
        [0.8582, 0.2755, 0.3892]])
Arange: tensor([0, 2, 4, 6, 8])
Full of 42s:
tensor([[42, 42, 42],
        [42, 42, 42]])


### 1.3 Data types matter!

Neural networks need **FLOAT tensors** (float32)!

In [4]:
# By default, integers -> int64, decimals -> float32
int_tensor   = torch.tensor([1, 2, 3])
float_tensor = torch.tensor([1.0, 2.0, 3.0])

print(f"Integer tensor dtype: {int_tensor.dtype}")    # torch.int64
print(f"Float tensor dtype: {float_tensor.dtype}")    # torch.float32

# You'll use this conversion A LOT:
converted = int_tensor.float()   # int -> float
print(f"After .float(): {converted.dtype}")  # torch.float32

# Other ways:
half_precision = float_tensor.half()     # float16 - uses less memory
double_precision = float_tensor.double() # float64 - more precise

Integer tensor dtype: torch.int64
Float tensor dtype: torch.float32
After .float(): torch.float32


---
## Part 2: Tensor Operations - Math with Tensors

These are the operations your neural network does internally!

### 2.1 Basic math

In [5]:
a = torch.tensor([1.0, 2.0, 3.0])
b = torch.tensor([4.0, 5.0, 6.0])

print(f"a = {a}")
print(f"b = {b}")
print(f"a + b = {a + b}")           # Element-wise addition
print(f"a - b = {a - b}")           # Element-wise subtraction
print(f"a * b = {a * b}")           # Element-wise multiplication (NOT matrix multiply!)
print(f"a / b = {a / b}")           # Element-wise division
print(f"a ** 2 = {a ** 2}")         # Element-wise power

# Useful aggregations
print(f"\nsum  = {a.sum()}")        # Total of all elements
print(f"mean = {a.mean()}")         # Average
print(f"max  = {a.max()}")          # Maximum value
print(f"min  = {a.min()}")          # Minimum value
print(f"argmax = {a.argmax()}")     # INDEX of maximum value

a = tensor([1., 2., 3.])
b = tensor([4., 5., 6.])
a + b = tensor([5., 7., 9.])
a - b = tensor([-3., -3., -3.])
a * b = tensor([ 4., 10., 18.])
a / b = tensor([0.2500, 0.4000, 0.5000])
a ** 2 = tensor([1., 4., 9.])

sum  = 6.0
mean = 2.0
max  = 3.0
min  = 1.0
argmax = 2


### 2.2 Matrix multiplication (THE key operation in deep learning!)

This is what happens inside EVERY neural network layer.

**Rule:** `(m x n) @ (n x p) -> (m x p)` - inner dimensions must match!

In [ ]:
X = torch.tensor([[0.1, 0.2], 
                  [0.3, 0.4], 
                  [0.5, 0.6]])

W = torch.tensor([[1.0, 2.0, 3.0], 
                  [4.0, 5.0, 6.0]])  # shape: 2x3

result = X @ W                      # shape: 3x3 (3x2 @ 2x3)
# Same as: torch.matmul(X, W)

print(f"X shape: {X.shape}")
print(f"W shape: {W.shape}")
print(f"X @ W shape: {result.shape}")
print(f"Result:\n{result}")

# WHY this matters: In a neural network layer:
#   output = input @ weights + bias
# That's literally it! A neural network is just matrix math + activation functions.

X shape: torch.Size([3, 2])
W shape: torch.Size([2, 3])
X @ W shape: torch.Size([3, 3])
Result:
tensor([[0.9000, 1.2000, 1.5000],
        [1.9000, 2.6000, 3.3000],
        [2.9000, 4.0000, 5.1000]])


### 2.3 Reshaping tensors

In [3]:
import torch
x = torch.arange(12)               # [0, 1, 2, ..., 11] - shape: (12,)
print(f"Original: {x} shape: {x.shape}")

reshaped = x.reshape(3, 4)         # Reshape to 3 rows, 4 columns
print(f"Reshaped to (3,4):\n{reshaped}")

reshaped2 = x.reshape(2, -1)       # -1 means "figure it out automatically"
print(f"Reshaped to (2,-1):\n{reshaped2}")  # becomes (2, 6)

# view() - same as reshape but shares memory (faster)
viewed = x.view(4, 3)
print(f"View (4,3):\n{viewed}")

Original: tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]) shape: torch.Size([12])
Reshaped to (3,4):
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
Reshaped to (2,-1):
tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])
View (4,3):
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])


### 2.4 Squeeze & Unsqueeze

Add/remove dimensions of size 1. You'll use this **A LOT** to make tensor shapes compatible.

In [5]:
import torch
a = torch.tensor([1.0, 2.0, 3.0])  # shape: (3,)
print(f"Original shape: {a.shape}")

b = a.unsqueeze(0)                  # Add dim at position 0 -> shape: (1, 3)
print(f"unsqueeze(0): {b.shape}")   # Like making a row vector

c = a.unsqueeze(1)                  # Add dim at position 1 -> shape: (3, 1)
print(f"unsqueeze(1): {c.shape}")   # Like making a column vector

d = b.squeeze()                     # Remove all dims of size 1 -> back to (3,)
print(f"squeeze(): {d.shape}")

Original shape: torch.Size([3])
unsqueeze(0): torch.Size([1, 3])
unsqueeze(1): torch.Size([3, 1])
squeeze(): torch.Size([3])


---
## Part 3: GPU - Make it FAST!

Your NVIDIA GPU can do math **10-100x faster** than your CPU. Moving tensors to GPU = instant speed boost.

In [1]:
import torch
# Best practice: set device automatically
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

if torch.cuda.is_available():
    # Create a tensor on GPU directly
    gpu_tensor = torch.rand(3, 3, device=device)
    print(f"GPU tensor device: {gpu_tensor.device}")

    # Move existing tensor to GPU
    cpu_tensor = torch.rand(3, 3)
    gpu_tensor2 = cpu_tensor.to(device)     # CPU -> GPU
    print(f"Moved to: {gpu_tensor2.device}")

    # Move back to CPU (needed for numpy, printing, etc.)
    back_to_cpu = gpu_tensor2.cpu()        # or .to("cpu")
    print(f"Back to: {back_to_cpu.device}")

    # IMPORTANT: You can't mix CPU and GPU tensors!
    # cpu_tensor + gpu_tensor  <-- This would ERROR!
    # Both must be on the same device.
else:
    print("No GPU available - everything runs on CPU (still works, just slower)")

Using device: cuda
GPU tensor device: cuda:0
Moved to: cuda:0
Back to: cpu


---
## Part 4: NumPy <-> PyTorch Conversion

You already know NumPy! Good news: they convert easily.

In [8]:
import numpy as np

# NumPy -> PyTorch
np_array = np.array([1.0, 2.0, 3.0])
tensor_from_np = torch.from_numpy(np_array)    # Shares memory!
print(f"NumPy: {np_array} -> Tensor: {tensor_from_np}")

# PyTorch -> NumPy
my_tensor = torch.tensor([4.0, 5.0, 6.0])
np_from_tensor = my_tensor.numpy()              # Shares memory!
print(f"Tensor: {my_tensor} -> NumPy: {np_from_tensor}")

# If tensor is on GPU, must move to CPU first:
# gpu_tensor.cpu().numpy()

# This is exactly what you did in deep_learning.ipynb Cell 3:
#   X_train_t = torch.FloatTensor(X_train)  <-- numpy to tensor!

NumPy: [1. 2. 3.] -> Tensor: tensor([1., 2., 3.], dtype=torch.float64)
Tensor: tensor([4., 5., 6.]) -> NumPy: [4. 5. 6.]


---
## Part 5: Autograd - PyTorch Learns From Mistakes!

This is **THE magic** of PyTorch. It automatically computes gradients (derivatives) - telling the model HOW to improve.

Think of it like this:
1. You make a prediction (forward pass)
2. You check how wrong you are (loss)
3. PyTorch traces back and says *"adjust THIS weight by THIS much"*
4. That's autograd! (automatic gradient computation)

In [ ]:
import torch
# Best practice: set device automatically
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

if torch.cuda.is_available():
    # Create a tensor on GPU directly
    gpu_tensor = torch.rand(3, 3, device=device)
    print(f"GPU tensor device: {gpu_tensor.device}")

    # Move existing tensor to GPU
    cpu_tensor = torch.rand(3, 3)
    gpu_tensor2 = cpu_tensor.to(device)     # CPU -> GPU
    print(f"Moved to: {gpu_tensor2.device}")

    # Move back to CPU (needed for numpy, printing, etc.)
    back_to_cpu = gpu_tensor2.cpu()        # or .to("cpu")
    print(f"Back to: {back_to_cpu.device}")

    # IMPORTANT: You can't mix CPU and GPU tensors!
    # cpu_tensor + gpu_tensor  <-- This would ERROR!
    # Both must be on the same device.
else:
    print("No GPU available - everything runs on CPU (still works, just slower)")

Using device: cuda
GPU tensor device: cuda:0
Moved to: cuda:0
Back to: cpu


### 5.1 Simple example: y = x^2

If y = x^2, then dy/dx = 2x (from calculus). Let's let PyTorch figure this out automatically!

In [3]:
x = torch.tensor(3.0, requires_grad=True)  # <-- Tell PyTorch to track this!
y = x ** 2                                   # y = 9

print(f"x = {x}")
print(f"y = x^2 = {y}")

y.backward()    # <-- Compute gradients! (backpropagation)

print(f"dy/dx = {x.grad}")  # Should be 2*3 = 6.0
# PyTorch computed the derivative automatically!

x = 3.0
y = x^2 = 9.0
dy/dx = 6.0


### 5.2 More complex example

In [4]:
x = torch.tensor(2.0, requires_grad=True)
y = x**3 + 2*x**2 + 5*x + 1   # y = x^3 + 2x^2 + 5x + 1
                                  # dy/dx = 3x^2 + 4x + 5
y.backward()
print(f"y = x^3 + 2x^2 + 5x + 1 at x=2")
print(f"dy/dx = 3x^2 + 4x + 5 = {x.grad}")  # 3(4) + 4(2) + 5 = 25.0

y = x^3 + 2x^2 + 5x + 1 at x=2
dy/dx = 3x^2 + 4x + 5 = 25.0


### 5.3 How this works in neural networks

Imagine a TINY network: `output = input * weight + bias`

In [8]:
torch.manual_seed(42)
input_val  = torch.tensor(2.0)
weight     = torch.tensor(0.5, requires_grad=True)   # learnable!
bias       = torch.tensor(0.1, requires_grad=True)   # learnable!
target     = torch.tensor(5.0)                         # what we WANT

# Forward pass: make a prediction
prediction = input_val * weight + bias  # 2.0 * 0.5 + 0.1 = 1.1
print(f"Prediction: {prediction.item():.2f}")
print(f"Target: {target.item():.2f}")

# Calculate loss: how wrong are we?
loss = (prediction - target) ** 2       # squared error = (1.1 - 5.0)^2 = 15.21
print(f"Loss: {loss.item():.2f}")

# Backward pass: compute gradients
loss.backward()
print(f"Weight gradient: {weight.grad:.4f}")  # tells us how to adjust weight
print(f"Bias gradient: {bias.grad:.4f}")      # tells us how to adjust bias

# Update weights (this is what optimizer.step() does!)
learning_rate = 0.01
with torch.no_grad():  # don't track these updates
    weight -= learning_rate * weight.grad   # nudge weight in right direction
    bias   -= learning_rate * bias.grad     # nudge bias in right direction

new_prediction = input_val * weight + bias
print(f"\nAfter 1 update: prediction = {new_prediction.item():.2f} (closer to 5.0!)")

Prediction: 1.10
Target: 5.00
Loss: 15.21
Weight gradient: -15.6000
Bias gradient: -7.8000

After 1 update: prediction = 1.49 (closer to 5.0!)


> **This is ALL a neural network does:**
> 1. **Forward pass** -> make prediction
> 2. **Calculate loss** -> how wrong?
> 3. **Backward pass** -> compute gradients (autograd magic!)
> 4. **Update weights** -> learn from mistakes
> 5. **Repeat!**

---
## Part 6: Activation Functions - Adding "Thinking" Power

Without activation functions, a neural network is just matrix multiplication - it can only learn **straight lines!** Activation functions add curves/non-linearity.

In [9]:
x = torch.linspace(-5, 5, 11)  # [-5, -4, ..., 4, 5]

# ReLU - most popular! Returns max(0, x)
relu = torch.nn.functional.relu(x)
print(f"Input:  {x.tolist()}")
print(f"ReLU:   {relu.tolist()}")
# Negative -> 0, Positive -> unchanged. Simple but powerful!

# Sigmoid - squishes everything between 0 and 1
sigmoid = torch.sigmoid(x)
print(f"Sigmoid: {[f'{v:.2f}' for v in sigmoid.tolist()]}")
# Perfect for probability/binary classification (cancer yes/no)

# Tanh - squishes between -1 and 1
tanh = torch.tanh(x)
print(f"Tanh:    {[f'{v:.2f}' for v in tanh.tolist()]}")

# You used these in deep_learning.ipynb Cell 4:
#   nn.ReLU()    - between hidden layers (adds non-linearity)
#   nn.Sigmoid() - final layer (converts output to probability 0-1)

Input:  [-5.0, -4.0, -3.0, -2.0, -1.0, 0.0, 1.0, 2.0, 3.0, 4.0, 5.0]
ReLU:   [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 2.0, 3.0, 4.0, 5.0]
Sigmoid: ['0.01', '0.02', '0.05', '0.12', '0.27', '0.50', '0.73', '0.88', '0.95', '0.98', '0.99']
Tanh:    ['-1.00', '-1.00', '-1.00', '-0.96', '-0.76', '0.00', '0.76', '0.96', '1.00', '1.00', '1.00']


---
## Part 7: Building a Neural Network with nn.Module

This is the standard way to build networks in PyTorch. Every model inherits from `nn.Module`.

### 7.1 A single layer (Linear)

`nn.Linear(in_features, out_features)` = `input @ weight.T + bias`

In [8]:
import torch.nn as nn

layer = nn.Linear(3, 2)  # 3 inputs -> 2 outputs

print("Single layer:")
print(f"  Weight shape: {layer.weight.shape}")  # (2, 3)
print(f"  Bias shape: {layer.bias.shape}")      # (2,)

sample_input = torch.tensor([1.0, 2.0, 3.0])
output = layer(sample_input)
print(f"  Input: {sample_input} -> Output: {output}")

Single layer:
  Weight shape: torch.Size([2, 3])
  Bias shape: torch.Size([2])
  Input: tensor([1., 2., 3.]) -> Output: tensor([-1.2422, -1.7479], grad_fn=<ViewBackward0>)


### 7.2 Build a full network

In [9]:
class SimpleNet(nn.Module):
    def __init__(self):
        super().__init__()
        # Define layers
        self.layer1 = nn.Linear(4, 8)     # 4 inputs -> 8 hidden neurons
        self.layer2 = nn.Linear(8, 4)     # 8 -> 4 hidden neurons
        self.layer3 = nn.Linear(4, 1)     # 4 -> 1 output
        self.relu = nn.ReLU()
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        # Define how data flows through the layers
        x = self.relu(self.layer1(x))     # Layer 1 + ReLU
        x = self.relu(self.layer2(x))     # Layer 2 + ReLU
        x = self.sigmoid(self.layer3(x))  # Layer 3 + Sigmoid (output 0-1)
        return x

model = SimpleNet()
print(f"Model:\n{model}")

# Count parameters (weights + biases the model will learn)
total_params = sum(p.numel() for p in model.parameters())
print(f"Total learnable parameters: {total_params}")

# Test with random input
test_input = torch.rand(1, 4)  # 1 sample, 4 features
test_output = model(test_input)
print(f"Test input shape: {test_input.shape}")
print(f"Test output: {test_output.item():.4f} (probability between 0 and 1)")

Model:
SimpleNet(
  (layer1): Linear(in_features=4, out_features=8, bias=True)
  (layer2): Linear(in_features=8, out_features=4, bias=True)
  (layer3): Linear(in_features=4, out_features=1, bias=True)
  (relu): ReLU()
  (sigmoid): Sigmoid()
)
Total learnable parameters: 81
Test input shape: torch.Size([1, 4])
Test output: 0.4812 (probability between 0 and 1)


### 7.3 nn.Sequential - shorthand

This is what your `CancerNet` uses in `deep_learning.ipynb`!

In [10]:
model_v2 = nn.Sequential(
    nn.Linear(4, 8),
    nn.ReLU(),
    nn.Linear(8, 4),
    nn.ReLU(),
    nn.Linear(4, 1),
    nn.Sigmoid()
)
print(f"Sequential model:\n{model_v2}")
# This is exactly the same network, just written more concisely!

Sequential model:
Sequential(
  (0): Linear(in_features=4, out_features=8, bias=True)
  (1): ReLU()
  (2): Linear(in_features=8, out_features=4, bias=True)
  (3): ReLU()
  (4): Linear(in_features=4, out_features=1, bias=True)
  (5): Sigmoid()
)


---
## Part 8: Loss Functions & Optimizers

- **Loss function** = measures how wrong the model is
- **Optimizer** = decides how to update weights to reduce loss

In [11]:
# --- Common Loss Functions ---
# Binary Cross Entropy - for binary classification (yes/no, cancer/no cancer)
bce_loss = nn.BCELoss()

# Mean Squared Error - for regression (predicting numbers)
mse_loss = nn.MSELoss()

# Cross Entropy - for multi-class classification (cat/dog/bird)
ce_loss = nn.CrossEntropyLoss()

# Example:
predictions = torch.tensor([0.8, 0.2, 0.9])  # model thinks: yes, no, yes
targets     = torch.tensor([1.0, 0.0, 1.0])   # actual: yes, no, yes
loss = bce_loss(predictions, targets)
print(f"BCE Loss: {loss.item():.4f}")  # low = good predictions!

BCE Loss: 0.1839


In [12]:
# --- Common Optimizers ---
model = SimpleNet()

# SGD - Stochastic Gradient Descent (classic, simple)
sgd = torch.optim.SGD(model.parameters(), lr=0.01)

# Adam - Adaptive (most popular, usually best to start with)
adam = torch.optim.Adam(model.parameters(), lr=0.001)

print(f"SGD optimizer: learning rate = {sgd.defaults['lr']}")
print(f"Adam optimizer: learning rate = {adam.defaults['lr']}")

# Learning rate (lr) = how big of a step to take
#   Too high -> overshoots, never learns
#   Too low  -> learns too slowly
#   0.001 is a good starting point for Adam

SGD optimizer: learning rate = 0.01
Adam optimizer: learning rate = 0.001


---
## Part 9: The Training Loop - Putting it ALL Together!

This is the **COMPLETE picture**. Everything above leads to this.

Let's train a tiny network to learn the **XOR pattern:**

| Input | Output |
|-------|--------|
| [0,0] | 0 |
| [0,1] | 1 |
| [1,0] | 1 |
| [1,1] | 0 |

In [13]:
# Setup data
X = torch.tensor([[0,0], [0,1], [1,0], [1,1]], dtype=torch.float32)
y = torch.tensor([[0],   [1],   [1],   [0]],   dtype=torch.float32)

# Build model
xor_model = nn.Sequential(
    nn.Linear(2, 8),
    nn.ReLU(),
    nn.Linear(8, 1),
    nn.Sigmoid()
)

# Setup loss and optimizer
criterion = nn.BCELoss()
optimizer = torch.optim.Adam(xor_model.parameters(), lr=0.01)

# THE TRAINING LOOP
print("Training XOR network...")
for epoch in range(1000):
    # 1. FORWARD PASS - make predictions
    predictions = xor_model(X)

    # 2. COMPUTE LOSS - how wrong are we?
    loss = criterion(predictions, y)

    # 3. BACKWARD PASS - compute gradients
    optimizer.zero_grad()   # Reset gradients (important!)
    loss.backward()         # Compute new gradients

    # 4. UPDATE WEIGHTS - learn!
    optimizer.step()

    # Print every 200 epochs
    if (epoch + 1) % 200 == 0:
        print(f"  Epoch {epoch+1}/1000 | Loss: {loss.item():.4f}")

Training XOR network...
  Epoch 200/1000 | Loss: 0.0640
  Epoch 400/1000 | Loss: 0.0117
  Epoch 600/1000 | Loss: 0.0048
  Epoch 800/1000 | Loss: 0.0026
  Epoch 1000/1000 | Loss: 0.0016


In [14]:
# Test the trained model
print("Results after training:")
with torch.no_grad():  # No need to track gradients for testing
    final_predictions = xor_model(X)
    for i in range(len(X)):
        pred = final_predictions[i].item()
        actual = y[i].item()
        print(f"  Input: {X[i].tolist()} -> Predicted: {pred:.3f} | Actual: {actual:.0f}")

Results after training:
  Input: [0.0, 0.0] -> Predicted: 0.002 | Actual: 0
  Input: [0.0, 1.0] -> Predicted: 0.998 | Actual: 1
  Input: [1.0, 0.0] -> Predicted: 0.998 | Actual: 1
  Input: [1.0, 1.0] -> Predicted: 0.002 | Actual: 0


---
## Summary - What you've learned:

| # | Topic | What it does |
|---|-------|-------------|
| 1 | **Tensors** | Containers for numbers (like numpy arrays but GPU-ready) |
| 2 | **Operations** | Math on tensors (especially matrix multiplication) |
| 3 | **GPU** | Move tensors to GPU with `.to(device)` for speed |
| 4 | **NumPy <-> PyTorch** | Easy conversion between numpy and pytorch |
| 5 | **Autograd** | PyTorch auto-computes gradients (the learning magic!) |
| 6 | **Activations** | ReLU, Sigmoid, Tanh add non-linearity |
| 7 | **nn.Module** | How to build neural networks |
| 8 | **Loss + Optimizer** | Measure error + update weights |
| 9 | **Training Loop** | Forward -> Loss -> Backward -> Update -> Repeat! |

**Now you're ready for `deep_learning.ipynb`!** That notebook applies everything you learned here to REAL cancer data.